### ISSUE TITLE
I have a problem, mine doesn't do anything

### ISSUE THREAD

**Issue by CaRLos1227** [bajrangCoder/acode-path-linker#2]
#

https://user-images.githubusercontent.com/96316594/232247086-a530e93d-48d3-4ffe-823a-b549b2ea9814.mp4

**Comment by bajrangCoder** [comment]
Only select the path , not inverted commas
In latest version it's removed because now it support alphabet in beginning and creates caos .

**Comment by CaRLos1227** [comment]
> Selecione apenas o caminho, não as vírgulas invertidas. Na versão mais recente, ele foi removido porque agora suporta o alfabeto no início e cria o caos.



> Only select the path , not inverted commas In latest version it's removed because now it support alphabet in beginning and creates caos .

Thanks, but I just did exactly what I saw you doing in the example video.

**Comment by CaRLos1227** [comment]
> Only select the path , not inverted commas In latest version it's removed because now it support alphabet in beginning and creates caos .

Thanks, but I just did what I saw you doing in the example video.

**Comment by bajrangCoder** [comment]
Ohh sorry 🥺.
